spring:
  main:
    sources: net.pavlafed.camelapigateway.CamelApiGatewayApplication

camel:
  springboot:
    name: ServicesRest
#    main-run-controller: true
  component:
    servlet:
      mapping:
        contextPath: '/api/*'

logging:
  level:
    org.apache.camel: DEBUG