spring:
  application:
    name: camel-api-gateway
  main:
    sources: net.pavlafed.camelapigateway.CamelApiGatewayApplication

server:
  port: 8090

camel:
  springboot:
    name: ServicesRest
#    main-run-controller: true
  component:
    servlet:
      mapping:
        contextPath: '/api/*'
  cloud:
    service-call:
      component: http4

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    org.apache.camel: DEBUG