spring:
  main:
    sources: net.pavlafed.camelapigateway.CamelApiGatewayApplication

camel:
  springboot:
    name: ServicesRest
#    main-run-controller: true

logging:
  level:
    org.apache.camel: DEBUG